	;ASSIGNMENT 2 QUESTION 1
	;WALP TO CHECK WHETHER A STRING STORED IN CODE MEMORY IS PALINDROME OR NOT
	;STORE 0XFF IN THE RAM IF PALINDROME, ELSE STORE 0X00
	
	AREA RESET, DATA, READONLY
	EXPORT __Vectors
__Vectors
	DCD 0x40000000
	DCD Reset_Handler
	ALIGN
	AREA mycode, CODE, READONLY
	ENTRY
	EXPORT Reset_Handler
Reset_Handler
	LDR R0, =SRC	
	LDR R1, =LENGTH		;WE ASSUME THE STRING'S LENGTH TO BE STORED IN THE CODE MEMORY
	LDR R1, [R1]		;R1 STORES THE STRING'S LENGTH
	ADD R2, R0, R1
	SUB R2, #01
	LSR R1, #01			;DIVIDES THE LENGTH OF THE STRING BY 2
	
	MOV R9, #0XFF
	
LOOP
	LDRB R3, [R0]
	LDRB R4, [R2]
	ADD R0, #01
	SUB R2, #01
	CMP R3, R4
	BEQ NEXT
	MOV R9, #0X00
	B EXIT
NEXT
	SUB R1, #01
	TEQ R1, #00
	BNE LOOP
	
EXIT
	LDR R8, =RES
	STR R9, [R8]
	
	
STOP B STOP

SRC DCB "345643"	;STRING OPERANDS CAN ONLY BE SPECIFIED FOR DCB
LENGTH DCD 6		;STORES LENGTH OF STRING

	AREA myarea, DATA, READWRITE
	
	
RES DCD 0
	END
	
	
