    AREA RESET,DATA,READONLY
	EXPORT __Vectors
__Vectors
	DCD 0X40000000
	DCD Reset_Handler
	ALIGN
	AREA mycode,CODE,READONLY
	ENTRY
	EXPORT Reset_Handler
Reset_Handler
	 LDR R0,=VALUE1
	 LDR R1,=VALUE2
	 LDR R6,=RESULT
	 LDR R2,[R0]
	 LDR R3,[R1]
     
	 
UP	 CMP R2,R3
     BEQ SAME1
     BCC DOWN1
     SUB R2,R2,R3
	 B UP
DOWN1 
     SUB R3,R3,R2
     B UP
SAME1
     MOV R5,R2
     STR R5,[R6]
STOP B STOP
VALUE1 DCD 0X12
VALUE2 DCD 0X8
	AREA data,DATA,READWRITE
RESULT DCD 0	
	END