    AREA RESET,DATA,READONLY
	EXPORT __Vectors
__Vectors
	DCD 0X40000000
	DCD Reset_Handler
	ALIGN
	AREA mycode,CODE,READONLY
	ENTRY
	EXPORT Reset_Handler
Reset_Handler
    
	LDR R0,=VALUE1
	LDR R1,[R0]
	LDR R2,=VALUE2
	LDR R3,[R2]
	LDR R5,=RESULT
	MOV R6,#5
UP  
	ADDS R7,R1
    SUB R6,#1
	TEQ R6,#0
	BNE UP
	
STOP B STOP
VALUE1 DCD 0X1234
VALUE2 DCD 0X5
	AREA data,DATA,READWRITE
RESULT DCD 0
	END 
	