    AREA RESET, DATA, READONLY
	EXPORT __Vectors
__Vectors
	DCD 0x10001000
	DCD Reset_Handler
	ALIGN
	AREA myCode6, CODE, READONLY
	ENTRY
	EXPORT Reset_Handler

Reset_Handler
	
	LDR R0, =NUM1
	LDR R1, [R0]
	LDR R0, =NUM2
	LDR R2, [R0]
	MOV R3,R1
	MOV R4,R2
UP	CMP R3,R4
	BEQ EXIT
	ADDHI R4,R4,R2
	ADDLO R3,R3,R1
	B UP
EXIT	
    LDR R0,=RESULT
	STR R4,[R0]
STOP B STOP
NUM1 DCD 9
NUM2 DCD 6
	AREA DATASEG, DATA, READWRITE
RESULT DCD 0
	END